//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Topper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string HOB { get; set; }
        public string BranchAddress { get; set; }
        public string MobileCode { get; set; }
        public string BranchMobileNo { get; set; }
        public string PhoneCode { get; set; }
        public string BranchPhoneNo { get; set; }
        public string BranchEmailID { get; set; }
        public Nullable<int> BranchStrengh { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creator { get; set; }
        public Nullable<int> Status { get; set; }
        public string Website { get; set; }
        public string ActivationCode { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
