//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Topper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public long ID { get; set; }
        public string CompanyName { get; set; }
        public string CEOName { get; set; }
        public string WebsiteUrl { get; set; }
        public string LogoPath { get; set; }
        public Nullable<long> Contact_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string CompanyType { get; set; }
    }

    public partial class Data_Return
    {
        public int saveStatus { get; set; }
        public long Created_ID { get; set; }

    }
}
