//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Topper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT_MASTER
    {
        public int ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
