//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent.Topper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PERMISSION
    {
        public long ID { get; set; }
        public Nullable<long> MenuID { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<bool> B_Add { get; set; }
        public Nullable<bool> B_Edit { get; set; }
        public Nullable<bool> B_Delete { get; set; }
        public Nullable<bool> B_View { get; set; }
        public Nullable<bool> B_Payment { get; set; }
        public Nullable<bool> Prient { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    }
}
